import { DailyRecommendation } from "../types";

export const DEFAULT_DAILY_RECOMMENDATIONS: DailyRecommendation[] = [
  {
    id: "rec_1",
    symbol: "TATAMOTORS",
    companyName: "Tata Motors Ltd",
    currency: "₹",
    currentPrice: 965.50,
    targetPrice: 1048.00,
    stopLoss: 928.00,
    expectedReturnPct: 8.55,
    signal: "STRONG BUY",
    timeframe: "1-3 Weeks",
    riskLevel: "Medium",
    category: "NSE India (Auto)",
    rationale: "Strong EV sales growth, margin expansion in JLR, and bullish momentum vector breakout.",
    keyCatalysts: ["JLR Margin Outperformance", "Domestic EV Market Leadership", "MACD Golden Cross"],
  },
  {
    id: "rec_2",
    symbol: "INFY",
    companyName: "Infosys Ltd",
    currency: "₹",
    currentPrice: 1842.00,
    targetPrice: 1985.00,
    stopLoss: 1770.00,
    expectedReturnPct: 7.76,
    signal: "BUY",
    timeframe: "2-4 Weeks",
    riskLevel: "Low",
    category: "NSE India (IT)",
    rationale: "Large deal wins in Cloud/AI integration with high 82% social sentiment consensus.",
    keyCatalysts: ["GenAI Enterprise Contracts", "BFSI Client Demand Revival", "Steady Dividend Yield"],
  },
  {
    id: "rec_3",
    symbol: "RELIANCE",
    companyName: "Reliance Industries",
    currency: "₹",
    currentPrice: 2985.00,
    targetPrice: 3220.00,
    stopLoss: 2880.00,
    expectedReturnPct: 7.87,
    signal: "ACCUMULATE",
    timeframe: "1 Month",
    riskLevel: "Low",
    category: "NSE India (Conglomerate)",
    rationale: "Jio telecom tariff hike monetization & Retail expansion driving free cash flows.",
    keyCatalysts: ["5G ARPU Uplift", "Jio Financial Synergies", "O2C Refining Margin Stability"],
  },
  {
    id: "rec_4",
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    currency: "$",
    currentPrice: 124.80,
    targetPrice: 142.00,
    stopLoss: 115.00,
    expectedReturnPct: 13.78,
    signal: "STRONG BUY",
    timeframe: "2-6 Weeks",
    riskLevel: "Medium",
    category: "US Tech (Semiconductors)",
    rationale: "Blackwell chip production ramp and overwhelming hyperscaler AI infrastructure capex.",
    keyCatalysts: ["Blackwell Data Center Demand", "Cloud Capex Supercycle", "AI SDK Dominance"],
  },
  {
    id: "rec_5",
    symbol: "TSLA",
    companyName: "Tesla, Inc.",
    currency: "$",
    currentPrice: 215.30,
    targetPrice: 248.00,
    stopLoss: 198.00,
    expectedReturnPct: 15.19,
    signal: "BUY",
    timeframe: "2-4 Weeks",
    riskLevel: "High",
    category: "US Tech (Auto/AI)",
    rationale: "Robotaxi fleet rollout momentum & Energy storage segment margin surge.",
    keyCatalysts: ["FSD Unsupervised Milestones", "Megapack Deployment Acceleration", "Model 2 Rumors"],
  },
  {
    id: "rec_6",
    symbol: "BTC",
    companyName: "Bitcoin",
    currency: "$",
    currentPrice: 64800.00,
    targetPrice: 72500.00,
    stopLoss: 60200.00,
    expectedReturnPct: 11.88,
    signal: "ACCUMULATE",
    timeframe: "2-8 Weeks",
    riskLevel: "High",
    category: "Crypto",
    rationale: "Institutional Spot ETF net inflows & post-halving supply squeeze consolidation.",
    keyCatalysts: ["Institutional ETF Inflows", "Macro Interest Rate Cuts", "On-Chain Accumulation"],
  },
];
