import { MutualFundSuggestion } from "../types";

export const SAMPLE_MUTUAL_FUNDS: MutualFundSuggestion[] = [
  {
    id: "mf-1",
    fundName: "ICICI Prudential Dividend Yield Equity Fund",
    category: "Dividend Yield",
    cagr3Y: 24.8,
    cagr5Y: 22.4,
    dividendYield: 3.85,
    expenseRatio: 0.62,
    aumInCr: 4850,
    riskRating: "Moderate",
    starRating: 5,
    fundHouse: "ICICI Prudential Mutual Fund",
    topHoldings: ["NTPC", "Coal India", "Power Grid", "Infosys", "ITC"],
    recommendedStrategy: "Regular Income & Dividends",
    currency: "₹",
    minSipAmount: 500,
    dividendFrequency: "Quarterly",
  },
  {
    id: "mf-2",
    fundName: "Schwab U.S. Dividend Equity ETF (SCHD)",
    category: "Dividend Yield",
    cagr3Y: 14.2,
    cagr5Y: 13.8,
    dividendYield: 3.52,
    expenseRatio: 0.06,
    aumInCr: 52000,
    riskRating: "Low",
    starRating: 5,
    fundHouse: "Charles Schwab Asset Management",
    topHoldings: ["Broadcom", "Home Depot", "Chevron", "AbbVie", "PepsiCo"],
    recommendedStrategy: "Regular Income & Dividends",
    currency: "$",
    minSipAmount: 50,
    dividendFrequency: "Quarterly",
  },
  {
    id: "mf-3",
    fundName: "Parag Parikh Flexi Cap Fund",
    category: "Flexi Cap",
    cagr3Y: 22.5,
    cagr5Y: 21.8,
    dividendYield: 0.95,
    expenseRatio: 0.58,
    aumInCr: 68500,
    riskRating: "Moderate",
    starRating: 5,
    fundHouse: "PPFAS Mutual Fund",
    topHoldings: ["HDFC Bank", "Alphabet (Google)", "Bajaj Holdings", "ITC", "Microsoft"],
    recommendedStrategy: "Growth & Wealth Creation",
    currency: "₹",
    minSipAmount: 1000,
    dividendFrequency: "Annually",
  },
  {
    id: "mf-4",
    fundName: "Vanguard High Dividend Yield ETF (VYM)",
    category: "Dividend Yield",
    cagr3Y: 12.6,
    cagr5Y: 11.9,
    dividendYield: 3.12,
    expenseRatio: 0.06,
    aumInCr: 48000,
    riskRating: "Low",
    starRating: 5,
    fundHouse: "Vanguard Group",
    topHoldings: ["JPMorgan Chase", "ExxonMobil", "Johnson & Johnson", "Procter & Gamble", "Broadcom"],
    recommendedStrategy: "Regular Income & Dividends",
    currency: "$",
    minSipAmount: 50,
    dividendFrequency: "Quarterly",
  },
  {
    id: "mf-5",
    fundName: "Nippon India Small Cap Fund",
    category: "Mid Cap",
    cagr3Y: 31.4,
    cagr5Y: 28.6,
    dividendYield: 0.45,
    expenseRatio: 0.68,
    aumInCr: 51200,
    riskRating: "Very High",
    starRating: 5,
    fundHouse: "Nippon India Mutual Fund",
    topHoldings: ["Tube Investments", "HDFC Bank", "KPIT Tech", "Apar Industries", "Voltas"],
    recommendedStrategy: "Aggressive Growth",
    currency: "₹",
    minSipAmount: 100,
    dividendFrequency: "Annually",
  },
  {
    id: "mf-6",
    fundName: "SBI Bluechip Fund",
    category: "Large Cap",
    cagr3Y: 18.2,
    cagr5Y: 17.5,
    dividendYield: 1.42,
    expenseRatio: 0.82,
    aumInCr: 43200,
    riskRating: "Low",
    starRating: 4,
    fundHouse: "SBI Mutual Fund",
    topHoldings: ["Reliance Industries", "ICICI Bank", "L&T", "Infosys", "ITC"],
    recommendedStrategy: "Capital Preservation",
    currency: "₹",
    minSipAmount: 500,
    dividendFrequency: "Annually",
  },
  {
    id: "mf-7",
    fundName: "Invesco India Dividend Yield Fund",
    category: "Dividend Yield",
    cagr3Y: 23.1,
    cagr5Y: 20.6,
    dividendYield: 3.40,
    expenseRatio: 0.72,
    aumInCr: 3200,
    riskRating: "Moderate",
    starRating: 4,
    fundHouse: "Invesco Mutual Fund",
    topHoldings: ["Tata Steel", "Infosys", "TCS", "State Bank of India", "Bharat Petroleum"],
    recommendedStrategy: "Regular Income & Dividends",
    currency: "₹",
    minSipAmount: 500,
    dividendFrequency: "Quarterly",
  },
  {
    id: "mf-8",
    fundName: "Vanguard Information Technology ETF (VGT)",
    category: "Global / Tech",
    cagr3Y: 21.8,
    cagr5Y: 22.5,
    dividendYield: 0.72,
    expenseRatio: 0.10,
    aumInCr: 75000,
    riskRating: "High",
    starRating: 5,
    fundHouse: "Vanguard Group",
    topHoldings: ["Apple", "Microsoft", "Nvidia", "Broadcom", "Salesforce"],
    recommendedStrategy: "Aggressive Growth",
    currency: "$",
    minSipAmount: 100,
    dividendFrequency: "Quarterly",
  },
  {
    id: "mf-9",
    fundName: "HDFC Hybrid Equity Fund",
    category: "Debt & Hybrid",
    cagr3Y: 17.5,
    cagr5Y: 16.2,
    dividendYield: 2.85,
    expenseRatio: 0.78,
    aumInCr: 22400,
    riskRating: "Moderate",
    starRating: 4,
    fundHouse: "HDFC Mutual Fund",
    topHoldings: ["ICICI Bank", "HDFC Bank", "GOI 10Y Sovereign Bonds", "Reliance", "Infosys"],
    recommendedStrategy: "Regular Income & Dividends",
    currency: "₹",
    minSipAmount: 300,
    dividendFrequency: "Monthly",
  },
];
